// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RodajeIA.Web.Datos;

#nullable disable

namespace RodajeIA.Web.Datos.Migraciones
{
    [DbContext(typeof(RodajeDbContext))]
    partial class RodajeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ClipPersonaje", b =>
                {
                    b.Property<int>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonajesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClipId", "PersonajesId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("ClipPersonaje");
                });

            modelBuilder.Entity("EscenaPersonaje", b =>
                {
                    b.Property<int>("EscenaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonajesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EscenaId", "PersonajesId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("EscenaPersonaje");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Clip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EscenaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoEnPantalla")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EscenaId", "Numero")
                        .IsUnique();

                    b.ToTable("Clips");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Episodio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerieId", "Numero")
                        .IsUnique();

                    b.ToTable("Episodios");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Escena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iluminacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MomentoDelDia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PuestaEnEscena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodioId", "Numero")
                        .IsUnique();

                    b.ToTable("Escenas");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.LineaDialogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acotacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Personaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClipId", "Orden")
                        .IsUnique();

                    b.ToTable("LineasDialogo");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionFisica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heridas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Peinado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vestuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ClipPersonaje", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Clip", null)
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RodajeIA.Web.Datos.Personaje", null)
                        .WithMany()
                        .HasForeignKey("PersonajesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscenaPersonaje", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Escena", null)
                        .WithMany()
                        .HasForeignKey("EscenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RodajeIA.Web.Datos.Personaje", null)
                        .WithMany()
                        .HasForeignKey("PersonajesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Clip", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Escena", "Escena")
                        .WithMany("Clips")
                        .HasForeignKey("EscenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escena");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Episodio", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Serie", "Serie")
                        .WithMany("Episodios")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Escena", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Episodio", "Episodio")
                        .WithMany("Escenas")
                        .HasForeignKey("EpisodioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episodio");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.LineaDialogo", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Clip", "Clip")
                        .WithMany("Dialogos")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Personaje", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Serie", "Serie")
                        .WithMany("Personajes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Clip", b =>
                {
                    b.Navigation("Dialogos");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Episodio", b =>
                {
                    b.Navigation("Escenas");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Escena", b =>
                {
                    b.Navigation("Clips");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Serie", b =>
                {
                    b.Navigation("Episodios");

                    b.Navigation("Personajes");
                });
#pragma warning restore 612, 618
        }
    }
}
